# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b8d188c46c650d702bfb4a862056ac496af2181a56ec56bf0c4785eb97cf02b6ffd400caf46a96f7345194d822dd990ab6eb0bc1f375f54ea6faa3b45a07f1e

test:
  secret_key_base: 141d1bbf72a9d16146b20297f48af5f67fd1694bfb0d625cfc25758bc889f42e1d32a908723c591a5c37c4b0298218e5a8bdd0b21f615cd5aa9eeceffc731ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
